### DISCUSSION TITLE
v1.0.1

### DISCUSSION THREAD

**Discussion by tisonkun** [korandoru/hawkeye#25] [Announcements]
# HawkEye 1.0.1

Simple license header checker and formatter, in multiple distribution forms.

### Native Image

```shell
docker pull ghcr.io/korandoru/hawkeye-native:v1.0.1
docker run --rm -v $(pwd):/github/workspace ghcr.io/korandoru/hawkeye-native:v1.0.1 check -h
```

### Executable JAR

This executable requires JRE 17+ existence.

```shell
wget https://repo1.maven.org/maven2/io/korandoru/hawkeye/commandline/1.0.1/commandline-1.0.1-bin.tar.gz
tar -xvzf commandline-1.0.1-bin.tar.gz
hawkeye-1.0.1/hawkeye check -h
```

### JRE Image

```shell
docker pull ghcr.io/korandoru/hawkeye:v1.0.1
docker run --rm -v $(pwd):/github/workspace ghcr.io/korandoru/hawkeye:v1.0.1 check -h
```

### GitHub Actions

```yaml
# prerequisite: add a `licenserc.toml` file in the root of your project
- name: Check License Header
  uses: korandoru/hawkeye@v1
```

## What's Changed
* chore: Prepare 1.0.1 by @tisonkun in https://github.com/korandoru/hawkeye/pull/23

**Full Changelog**: https://github.com/korandoru/hawkeye/compare/v1.0.0...v1.0.1

<hr /><em>This discussion was created from the release <a href='https://github.com/korandoru/hawkeye/releases/tag/v1.0.1'>v1.0.1</a>.</em>
