### DISCUSSION TITLE
v1.0.2

### DISCUSSION THREAD

**Discussion by tisonkun** [korandoru/hawkeye#26] [Announcements]
# HawkEye 1.0.2

Simple license header checker and formatter, in multiple distribution forms.

### Native Image

```shell
docker run --rm -v $(pwd):/github/workspace ghcr.io/korandoru/hawkeye-native:v1.0.2 check -h
```

### Executable JAR

This executable requires JRE 17+ existence.

```shell
export HAWKEYE_VERSION=1.0.2
wget https://repo1.maven.org/maven2/io/korandoru/hawkeye/commandline/$HAWKEYE_VERSION/commandline-$HAWKEYE_VERSION-bin.tar.gz
tar -xvzf commandline-$HAWKEYE_VERSION-bin.tar.gz
hawkeye-$HAWKEYE_VERSION/hawkeye check -h
```

### JRE Image

```shell
docker run --rm -v $(pwd):/github/workspace ghcr.io/korandoru/hawkeye:v1.0.2 check -h
```

### GitHub Actions

```yaml
# prerequisite: add a `licenserc.toml` file in the root of your project
- name: Check License Header
  uses: korandoru/hawkeye@v1
```

## What's Changed

* fix: follow links on walkFileTree b2942306dab2627f5a41b51c89a5d017c938ac76
* fix: complete results future of selectedFiles a8e29b73e655f143e3a25bd5dc02f079a3ec4414

**Full Changelog**: https://github.com/korandoru/hawkeye/compare/v1.0.1...v1.0.2

<hr /><em>This discussion was created from the release <a href='https://github.com/korandoru/hawkeye/releases/tag/v1.0.2'>v1.0.2</a>.</em>
