### DISCUSSION TITLE
v1.0.3

### DISCUSSION THREAD

**Discussion by tisonkun** [korandoru/hawkeye#28] [Announcements]
# HawkEye 1.0.3

Simple license header checker and formatter, in multiple distribution forms.

### Native Image

```shell
docker run --rm -v $(pwd):/github/workspace ghcr.io/korandoru/hawkeye-native:v1.0.3 check -h
```

### Executable JAR

This executable requires JRE 17+ existence.

```shell
export HAWKEYE_VERSION=1.0.3
wget https://repo1.maven.org/maven2/io/korandoru/hawkeye/commandline/$HAWKEYE_VERSION/commandline-$HAWKEYE_VERSION-bin.tar.gz
tar -xvzf commandline-$HAWKEYE_VERSION-bin.tar.gz
hawkeye-$HAWKEYE_VERSION/hawkeye check -h
```

### JRE Image

```shell
docker run --rm -v $(pwd):/github/workspace ghcr.io/korandoru/hawkeye:v1.0.3 check -h
```

### GitHub Actions

```yaml
# prerequisite: add a `licenserc.toml` file in the root of your project
- name: Check License Header
  uses: korandoru/hawkeye@v1
```

## What's Changed

This version is mainly to refactor build logics.

* build(maven): Try preparationGoals and completionGoals by @tisonkun in https://github.com/korandoru/hawkeye/pull/27

**Full Changelog**: https://github.com/korandoru/hawkeye/compare/v1.0.2...v1.0.3

<hr /><em>This discussion was created from the release <a href='https://github.com/korandoru/hawkeye/releases/tag/v1.0.3'>v1.0.3</a>.</em>
