### DISCUSSION TITLE
v1.1.0

### DISCUSSION THREAD

**Discussion by tisonkun** [korandoru/hawkeye#30] [Announcements]
# HawkEye 1.1.0

Simple license header checker and formatter, in multiple distribution forms.

### Native Image

```shell
docker run --rm -v $(pwd):/github/workspace ghcr.io/korandoru/hawkeye-native:v1.1.0 check -h
```

### Executable JAR

This executable requires JRE 17+ existence.

```shell
export HAWKEYE_VERSION=1.1.0
wget https://repo1.maven.org/maven2/io/korandoru/hawkeye/commandline/$HAWKEYE_VERSION/commandline-$HAWKEYE_VERSION-bin.tar.gz
tar -xvzf commandline-$HAWKEYE_VERSION-bin.tar.gz
hawkeye-$HAWKEYE_VERSION/hawkeye check -h
```

### JRE Image

```shell
docker run --rm -v $(pwd):/github/workspace ghcr.io/korandoru/hawkeye:v1.1.0 check -h
```

### GitHub Actions

```yaml
# prerequisite: add a `licenserc.toml` file in the root of your project
- name: Check License Header
  uses: korandoru/hawkeye@v1
```

## What's Changed

* feat: Add Rust file support and update some predefinitions by @tisonkun in https://github.com/korandoru/hawkeye/pull/29

**Full Changelog**: https://github.com/korandoru/hawkeye/compare/v1.0.0...v1.1.0

<hr /><em>This discussion was created from the release <a href='https://github.com/korandoru/hawkeye/releases/tag/v1.1.0'>v1.1.0</a>.</em>
