### ISSUE TITLE
Use prebuilt binaries in the GitHub action

### ISSUE THREAD

**Issue by pstoeckle** [korandoru/hawkeye#189]
## Problem 

Currently, the GitHub Action compiles the `hawkeye` binary every time before checking the files. Checking the files is under 1s, compiling over 2min.

## (Potential) Solution

Download and use the prebuilt binaries. One could include `curl --proto '=https' --tlsv1.2 -LsSf https://github.com/korandoru/hawkeye/releases/download/v6.1.1/hawkeye-installer.sh | sh` or a variation of it to the `action.yml` instead of the compilation.

**Comment by tisonkun** [comment]
Sounds reasonable. I remember that previously the action was implemented in this way but it may require extra code bump just for release.

That said, you need to keep the version number and tag name matched.

**Comment by tisonkun** [comment]
If we change to prebuilt binary or images, I'm afraid the dependency would be unreliable during the releasing phase. And on the main branch, we'd always build from source.

I can suggest either:

1. Use docker run like:

```yaml
      - name: Check license header
        env:
          IMAGE: ghcr.io/korandoru/hawkeye:v6
          CONFIG: tools/ci/licenserc.toml
        run: docker run --rm -v $(pwd):/github/workspace ${IMAGE} check --config ${CONFIG}
```

2. Tag something like `uses: korandoru/hawkeye@docker-v6` manually/automatically after each release succeeds.
