### ISSUE TITLE
Support user-defined header definitions

### ISSUE THREAD

**Issue by tisonkun** [korandoru/hawkeye#19]
`mapping` enables users to define their own mapping logic. And it's common for users to want to extend the HeaderDefinition that can be used.

The config structure can be:

```toml
[headerDefinitions.my_favorite_style]
firstLine = "..."
endLine = "..."
# ...
```

... and then referred in the `mapping` section:

```toml
[mapping]
rs = 'my_favorite_style'
```

References:

* [HeaderStyle](https://github.com/mathieucarbou/license-maven-plugin/blob/master/license-maven-plugin/src/main/java/com/mycila/maven/plugin/license/HeaderStyle.java) model
* [HeaderDefinition](https://github.com/mathieucarbou/license-maven-plugin/blob/master/license-maven-plugin/src/main/java/com/mycila/maven/plugin/license/header/HeaderDefinition.java) especially `setPropertiesFromString`
