### ISSUE TITLE
Cache Maven dependencies in CI workflow

### ISSUE THREAD

**Issue by tisonkun** [korandoru/hawkeye#73]
Currently, [unit tests on macOS](https://github.com/korandoru/hawkeye/actions/runs/4711050004/jobs/8355178931) consume over 20 minutes, which is relatively long for me. It seems the dependencies download step consumes the major time. Thus, we can improve the case by caching maven depedencies.

Related to -

https://github.com/korandoru/hawkeye/blob/2f4e49c7f3e81ce8ec79b07b4239fecb91579506/.github/workflows/ci.yml#L65-L72

[Ref impl](https://github.com/apache/pulsar/blob/6152cc82ac8a344cfc2539c56f15cec6f4a1cff7/.github/workflows/pulsar-ci.yaml#L121-L130) -

```yml
      - name: Cache local Maven repository
        uses: actions/cache@v3
        timeout-minutes: 5
        with:
          path: |
            ~/.m2/repository/*/*/*
            !~/.m2/repository/org/apache/pulsar
          key: ${{ runner.os }}-m2-dependencies-core-modules-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-m2-dependencies-core-modules-
```
